//! `forge codegen` — generate Rust types from ABI JSON.

use std::path::PathBuf;

use forge_index_core::abi::parser::parse_abi;
use forge_index_core::abi::types::{AbiEvent, AbiType};

/// Runs the codegen command: reads ABI JSON, writes Rust type definitions.
pub fn run(abi_path: PathBuf, output_dir: PathBuf, contract_name: String) -> anyhow::Result<()> {
    let abi_json = std::fs::read_to_string(&abi_path)
        .map_err(|e| anyhow::anyhow!("Failed to read {}: {}", abi_path.display(), e))?;

    let parsed = parse_abi(&abi_json).map_err(|e| anyhow::anyhow!("Failed to parse ABI: {}", e))?;

    let mut code = String::new();
    code.push_str("//! Auto-generated types for ");
    code.push_str(&contract_name);
    code.push_str(".\n//! Generated by `forge codegen`.\n\n");
    code.push_str("#![allow(dead_code)]\n\n");
    code.push_str("use forge_index::prelude::*;\n\n");

    // ABI constant
    code.push_str(&format!("/// The full ABI JSON for {}.\n", contract_name));
    code.push_str(&format!(
        "pub const {}_ABI: &str = include_str!(\"{}\");\n\n",
        contract_name.to_uppercase(),
        abi_path
            .canonicalize()
            .unwrap_or(abi_path.clone())
            .display()
    ));

    // Generate event structs
    let mut event_count = 0;
    for event in &parsed.events {
        code.push_str(&generate_event_struct(&contract_name, event));
        code.push('\n');
        event_count += 1;
    }

    // Write the file
    std::fs::create_dir_all(&output_dir)?;
    let output_file = output_dir.join(format!("{}.rs", contract_name.to_lowercase()));
    std::fs::write(&output_file, &code)?;

    println!(
        "Generated {} with {} event types",
        output_file.display(),
        event_count
    );

    Ok(())
}

/// Generates a Rust struct and impl block for an ABI event.
pub fn generate_event_struct(contract_name: &str, event: &AbiEvent) -> String {
    let struct_name = format!("{}Args", event.name);
    let mut code = String::new();

    // Doc comment
    code.push_str(&format!(
        "/// Event args for `{}.{}`.\n",
        contract_name, event.name
    ));
    code.push_str(&format!("/// Signature: `{}`\n", event.signature));

    // Derive
    code.push_str("#[derive(Debug, Clone)]\n");
    code.push_str(&format!("pub struct {} {{\n", struct_name));

    for param in &event.inputs {
        let rust_type = abi_type_to_rust(&param.abi_type);
        code.push_str(&format!(
            "    pub {}: {},\n",
            sanitize_name(&param.name),
            rust_type
        ));
    }

    code.push_str("}\n\n");

    // Impl block with constants
    code.push_str(&format!("impl {} {{\n", struct_name));
    code.push_str(&format!(
        "    pub const EVENT_NAME: &'static str = \"{}\";\n",
        event.name
    ));
    code.push_str(&format!(
        "    pub const SELECTOR: &'static str = \"{}\";\n",
        event.selector
    ));
    code.push_str("}\n");

    code
}

/// Converts an ABI type to a Rust type string.
fn abi_type_to_rust(abi_type: &AbiType) -> String {
    match abi_type {
        AbiType::Address => "Address".to_string(),
        AbiType::Bool => "bool".to_string(),
        AbiType::Uint(bits) if *bits <= 64 => "u64".to_string(),
        AbiType::Uint(bits) if *bits <= 128 => "u128".to_string(),
        AbiType::Uint(_) => "String".to_string(), // U256 as String
        AbiType::Int(bits) if *bits <= 64 => "i64".to_string(),
        AbiType::Int(bits) if *bits <= 128 => "i128".to_string(),
        AbiType::Int(_) => "String".to_string(),
        AbiType::FixedBytes(n) => format!("[u8; {}]", n),
        AbiType::Bytes => "Vec<u8>".to_string(),
        AbiType::String => "String".to_string(),
        AbiType::Array(inner) => format!("Vec<{}>", abi_type_to_rust(inner)),
        AbiType::FixedArray(inner, n) => format!("[{}; {}]", abi_type_to_rust(inner), n),
        AbiType::Tuple(params) => {
            let fields: Vec<String> = params
                .iter()
                .map(|p| abi_type_to_rust(&p.abi_type))
                .collect();
            format!("({})", fields.join(", "))
        }
    }
}

/// Sanitizes a parameter name to be a valid Rust identifier.
fn sanitize_name(name: &str) -> String {
    let name = if name.is_empty() { "unnamed" } else { name };
    // Handle Rust keywords
    match name {
        "type" | "self" | "Self" | "fn" | "mod" | "use" | "pub" | "let" | "mut" | "ref" | "as"
        | "in" | "for" | "if" | "else" | "return" | "match" | "loop" | "while" | "break"
        | "continue" | "struct" | "enum" | "trait" | "impl" | "where" | "move" => {
            format!("r#{}", name)
        }
        _ => name.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use forge_index_core::abi::parser::parse_abi;

    const ERC20_ABI: &str = r#"[
        {
            "type": "event",
            "name": "Transfer",
            "inputs": [
                {"name": "from", "type": "address", "indexed": true},
                {"name": "to", "type": "address", "indexed": true},
                {"name": "value", "type": "uint256", "indexed": false}
            ]
        },
        {
            "type": "event",
            "name": "Approval",
            "inputs": [
                {"name": "owner", "type": "address", "indexed": true},
                {"name": "spender", "type": "address", "indexed": true},
                {"name": "value", "type": "uint256", "indexed": false}
            ]
        }
    ]"#;

    #[test]
    fn codegen_generates_valid_rust() {
        let parsed = parse_abi(ERC20_ABI).unwrap();
        let code = generate_event_struct("ERC20", &parsed.events[0]);

        assert!(code.contains("pub struct TransferArgs"));
        assert!(code.contains("pub from: Address"));
        assert!(code.contains("pub to: Address"));
        assert!(code.contains("pub value: String")); // uint256 -> String
        assert!(code.contains("EVENT_NAME"));
        assert!(code.contains("SELECTOR"));
    }

    #[test]
    fn codegen_generates_correct_selector() {
        let parsed = parse_abi(ERC20_ABI).unwrap();
        let code = generate_event_struct("ERC20", &parsed.events[0]);

        assert!(code.contains("0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"));
    }

    #[test]
    fn codegen_creates_output_file() {
        let dir = tempfile::tempdir().unwrap();
        let abi_path = dir.path().join("erc20.json");
        std::fs::write(&abi_path, ERC20_ABI).unwrap();

        let output_dir = dir.path().join("generated");
        run(abi_path, output_dir.clone(), "ERC20".to_string()).unwrap();

        let output_file = output_dir.join("erc20.rs");
        assert!(output_file.exists(), "output file should exist");

        let content = std::fs::read_to_string(&output_file).unwrap();
        assert!(content.contains("pub struct TransferArgs"));
        assert!(content.contains("pub struct ApprovalArgs"));
    }
}
